env:
  AWS_DEFAULT_REGION: "ap-southeast-2"

steps:
  - name: ":package: building ruby test container"
    command : "cd ruby-tests; make all"

  - wait

  - name: ":package: building jre8"
    command : "cd jre8; make all"
